# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a846387cabd9f9040cd20789bd01dc715dde1284fd4945b227681a019d8e457f873d04c3d8a0360ee590484d8057af4d5a40e6234815a7b84f2f0d088f0c868

test:
  secret_key_base: 07215f415c71bfd26572197fbfc44b3aa8a8f329a17399468e475ea96cd32cf0b1a7536a3c47d2ec9f19ebdf4ba0a2a604d2982d56ac9e6d0d33b504b3c8b6c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
